FROM nginx:1.17.8-alpine

RUN mkdir /etc/nginx/tls
COPY conf/tls/*.crt /etc/nginx/tls/vault.crt
COPY conf/tls/*.key /etc/nginx/tls/vault.key

COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/nginx_vault.conf /etc/nginx/conf.d/vault.conf